name: yimages
description: Create and share beautiful Scrapbooks using Photos, Text and Stickers!
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  anchored_popups: ^0.1.0
  animate_do: ^2.1.0
  auto_size_text:
    git:
      url: https://github.com/brennan992k/auto_size_text.git
  bitsdojo_window: ^0.1.0+1
  cached_network_image: ^3.0.0
  cloudinary_public: ^0.8.0
  context_menus: ^0.1.0+5
  darq: ^1.0.0-dev.3
  desktop_window: ^0.4.0
  dotted_border: ^2.0.0-nullsafety.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.0-nullsafety.1
  flutter_lorem: ^2.0.0
  flextras: ^0.0.1
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_linux: ^0.0.2
  file_selector_web: ^0.8.1
  flutter_svg: ^0.22.0
  image_picker: ^0.8.0+4
  image_size_getter: ^1.0.0
  multi_image_picker: ^4.8.00
  path_provider: ^2.0.1
  provider: ^5.0.0
  random_color: ^1.0.6-nullsafety
  sized_context: ^1.0.0+1
  shared_preferences: ^2.0.4
  share: ^2.0.1
  system_info: ^1.0.0
  statsfl: ^2.0.1+1
  timeago: ^3.0.2
  universal_platform: ^1.0.0-nullsafety
  url_launcher: ^6.0.2
  uuid: ^3.0.1
  visibility_detector: ^0.2.2

  #FIREBASE
  firebase_core: 1.13.1
  firedart: ^0.9.0+1
  cloud_firestore: ^3.1.11
  firebase_auth: ^3.3.12

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.1
  freezed_annotation: ^0.14.1
  json_serializable:
  flutter_launcher_icons: ^0.9.0
  msix: ^2.8.13
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/app-flutter-folio.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/emoji/
    - assets/images/logos/
    - assets/images/landing_page/

  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces_72pt-SemiBold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/scraps/AlfaSlabOne-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/scraps/Amiri-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/scraps/Caveat-Medium.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/scraps/Lato-Regular.ttf
    - family: Mali
      fonts:
        - asset: assets/fonts/scraps/Mali-Medium.ttf
    - family: PathwayGothicOne
      fonts:
        - asset: assets/fonts/scraps/PathwayGothicOne-Regular.ttf
