// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOxeDbj9AGz2CbAKPmez0CNfwkUb8DPo',
    appId: '1:183196894352:web:9c97f8c30fabc54b080415',
    messagingSenderId: '183196894352',
    projectId: 'yimages',
    authDomain: 'yimages.firebaseapp.com',
    storageBucket: 'yimages.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcaUnBWKHRVOtXXNNpVQ3MPCXEvY9ZKZ8',
    appId: '1:183196894352:android:61442a8de825ec3f080415',
    messagingSenderId: '183196894352',
    projectId: 'yimages',
    storageBucket: 'yimages.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7vkhQnnFlLz46mr7cgz6hIn6WKsX5-c',
    appId: '1:183196894352:ios:7e61e043ce738b60080415',
    messagingSenderId: '183196894352',
    projectId: 'yimages',
    storageBucket: 'yimages.appspot.com',
    iosClientId: '183196894352-efe3a57t8p3abo1q5kq72p4a4a3fm82v.apps.googleusercontent.com',
    iosBundleId: 'net.themeplace.yimages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC7vkhQnnFlLz46mr7cgz6hIn6WKsX5-c',
    appId: '1:183196894352:ios:7e61e043ce738b60080415',
    messagingSenderId: '183196894352',
    projectId: 'yimages',
    storageBucket: 'yimages.appspot.com',
    iosClientId: '183196894352-efe3a57t8p3abo1q5kq72p4a4a3fm82v.apps.googleusercontent.com',
    iosBundleId: 'net.themeplace.yimages',
  );
}
